### ISSUE TITLE
Distinct descriptions for ECS frameworks

### ISSUE THREAD

**Issue by dasifefe** [dasifefe/rust-game-development-frameworks#3]
Apparently, each of the listed frameworks have some advantages/disadvantages. Would be helpful if someone with experience on those could send some descriptions. Might send even here in this thread, if that's easier.

**Comment by Ralith** [comment]
hecs' tl;dr is a minimalist, ergonomic API without performance compromises

**Comment by Systemcluster** [comment]
Shipyard is an "ECS focused on usability and speed built on the `EnTT` SparseSet structure." 

Hecs and Legion are Archetype-based, Specs is Bitset based; It might make sense to draw that distinction in their descriptions, or even link to [this overview](https://github.com/SanderMertens/ecs-faq#what-are-the-different-ways-to-implement-an-ecs) of those types.

It might also make sense to link to [ecs_bench_suite](https://github.com/rust-gamedev/ecs_bench_suite) somewhere.

**Comment by dasifefe** [comment]
Thank you. I agree that there's so much you can fit into an on-line description. Besides, most descriptions will be like "performance oriented, minimalist, bla bla". I decided to just inform which is the approach that each ECS uses (Archetype, Bitset, etc.) and I copy-pasted the information in the link that you provided.
