### ISSUE TITLE
GUI section

### ISSUE THREAD

**Issue by Ratysz** [dasifefe/rust-game-development-frameworks#6]
I absent-mindedly recommended this list as a source of information on GUI frameworks, only to realize that it does not contain anything of the sort.

Let's see if we can collect some libraries in this issue, and at some later point turn it into a PR creating the GUI section in the list?

The ones I'm familiar with, in no particular order:
- `imgui` https://docs.rs/imgui/
- `iced` https://docs.rs/iced/
- `egui` https://docs.rs/egui/

**Comment by dasifefe** [comment]
Thanks, Ratys, I updated the README.

**Comment by Ratysz** [comment]
I suppose this is resolved for now, then.
